-- creates table for user account data
CREATE TABLE col_users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email Text NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    password TEXT NOT NULL
);