CREATE TABLE col_events(
    id uuid PRIMARY KEY GENERATED BY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    event_desc TEXT,
    event_date DATE NOT NULL
);

ALTER TABLE col_events(
    ADD COLUMN
    user_id uuid REFERENCES col_users(id) on DELETE CASCADE NOT NULL
);