-- creates the table for users' phone numbers
CREATE TABLE phone_number (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    users_number BIGINT
);

ALTER TABLE phone_number
    ADD COLUMN
    user_id INTEGER REFERENCES col_users(id) ON DELETE CASCADE NOT NULL;
