-- creates the table for users' phone numbers
CREATE TABLE phone_number (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    phone_numbers INTEGER,
    user_id INTEGER REFERENCES col_users(id) NOT NULL
);